这是一个报错收集，



##### 主机无法工作的报错:

```json
2019-01-07 08:13:39,732+08 ERROR [org.ovirt.engine.core.bll.InitVdsOnUpCommand] (EE-ManagedThreadFactory-engine-Thread-2402) [5e5233b6] Could not connect host 'host91' to pool 'datacenter1': null
```



##### 挂载nfs超时

一般每个主机都应该有共享目录的，这样虚拟机才能正常开机，但是挂载可能因为源主机防火墙配置，导致挂载超时或者失败

```json
2019-01-07 08:17:07,427+08 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] EVENT_ID: VDS_STORAGES_CONNECTION_FAILED(188), Failed to connect Host host91 to the Storage Domains data89.
2019-01-07 08:17:07,427+08 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.ConnectStorageServerVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] FINISH, ConnectStorageServerVDSCommand, return: {84833af7-192c-40ef-9c10-646ca50c40ee=477}, log id: 3c7cc259
2019-01-07 08:17:07,431+08 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] EVENT_ID: STORAGE_DOMAIN_ERROR(996), The error message for connection 192.168.0.89:/export/data returned by VDSM was: Problem while trying to mount target
2019-01-07 08:17:07,431+08 ERROR [org.ovirt.engine.core.bll.storage.connection.FileStorageHelper] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] The connection with details '192.168.0.89:/export/data' failed because of error code '477' and error message is: problem while trying to mount target
```

